name: Render

on:
  push:
    branches: 
      - main

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install rendercv
        run: pip install rendercv
      - name: Update cv
        run: ./update.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv-output
          path: rendercv_output
  release:
    runs-on: ubuntu-latest
    needs: render
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: cv-output
      - name: GitHub Release
        uses: softprops/action-gh-release@v2.0.4
        with:
          files: rendercv_output
